"""Synthetic recordings generated by the twin itself, so tests know the true parameters."""

from __future__ import annotations

import dataclasses

import jax.numpy as jnp
import numpy as np
import pandas as pd
import pytest

from chhaya.data.schema import Recording
from chhaya.twin.inputs import build_inputs
from chhaya.twin.model import default_z, simulate_jit
from chhaya.units import mmol_to_mgdl

Z_SHIFT = np.array([0.25, -0.6, -0.5, 0.12, 0.5, 0.3, -0.15])


def make_recording(
    days: int = 6, seed: int = 0, z=None, noise_mmol: float = 0.4, with_ref: bool = False
) -> Recording:
    rng = np.random.default_rng(seed)
    n_min = days * 1440
    rows = []
    for d in range(days):
        for hour, carbs in ((8, 45), (13, 70), (20, 60)):
            rows.append(
                {
                    "t_min": float(d * 1440 + hour * 60 + rng.integers(-30, 30)),
                    "carb_g": carbs * rng.uniform(0.6, 1.4),
                    "protein_g": rng.uniform(5, 30),
                    "fat_g": rng.uniform(5, 30),
                    "fibre_g": rng.uniform(0, 10),
                    "label": "meal",
                }
            )
    met = np.ones(n_min)
    for d in range(days):
        met[d * 1440 + 18 * 60 : d * 1440 + 18 * 60 + 40] = 4.0
    activity = pd.DataFrame({"t_min": np.arange(n_min, dtype=float), "met": met, "hr": 70.0})
    z = default_z() + Z_SHIFT if z is None else np.asarray(z)
    fasting = float(mmol_to_mgdl(np.exp(z[3])))
    static = {
        "weight_kg": 70.0,
        "fasting_insulin_uu_ml": 12.0,
        "fasting_glucose_mgdl": fasting,
        "group": "t2d",
    }
    t = np.arange(0, n_min, 15)
    shell = Recording(
        rec_id=f"synth-{seed}",
        patient_id=f"synth-{seed}",
        dataset="synthetic",
        start=pd.Timestamp("2026-01-01 00:00"),
        n_min=n_min,
        cgm=pd.DataFrame({"t_min": t, "glucose_mgdl": np.full(t.size, fasting)}),
        static=static,
        meals=pd.DataFrame(rows),
        activity=activity,
    )
    inp, _, _ = build_inputs(shell)
    truth = np.asarray(simulate_jit(jnp.asarray(z), inp).gi)

    def sensor(step: int) -> pd.DataFrame:
        ts = np.arange(0, n_min, step)
        g = mmol_to_mgdl(truth[ts] + rng.normal(0.0, noise_mmol, ts.size))
        return pd.DataFrame({"t_min": ts, "glucose_mgdl": np.clip(g, 40.0, 400.0)})

    cgm = sensor(15)
    return dataclasses.replace(shell, cgm=cgm, cgm_ref=sensor(5) if with_ref else shell.cgm_ref)


@pytest.fixture(scope="session")
def rec() -> Recording:
    return make_recording()
